### PR TITLE
Use atom notification system to display errors/warnings

### PR DESCRIPTION
**Pull request by Marv51**

### CODE REVIEW

**Comment by rugk** [comment]
:+1: Nice idea!

**Comment by pfefferle** [comment]
Oh sorry, totally forgot that one... shame on me!

**Comment by pfefferle** [comment]
@rugk have you tried the change?

**Comment by rugk** [comment]
No, just liked the idea. :smiley:

**Comment by pfefferle** [comment]
@Marv51 thanks for the idea and the initial pull request. I just released a new version with some little changes: I changed the `warning` notification to an `info` and added a settings item to en/disable it.

**Pull request merged**
